### ISSUE TITLE
Property 'type' does not exist on type 'Asset'.ts

### ISSUE THREAD

**Issue by robinscholz** [Frontify/brand-sdk#323]
The Asset.ts file seems to be incomplete. The response coming back from `const { blockAssets } = useBlockAssets(appBridge)` is much more complex than what is currently typed here: https://github.com/Frontify/brand-sdk/blob/main/packages/app-bridge/src/types/Asset.ts

**Comment by SamuelAlev** [comment]
The untyped properties might change in the near future, we don't recommend to base yourself on them.

**Comment by robinscholz** [comment]
What do you reckon then? Writing types for things the app bridge exposes? Why are the types exposed by the package then?

**Comment by SamuelAlev** [comment]
Stale issue, please reopen if needed
